wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1679328265.670619
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.10.9
      5: 0.14.0
      8:
      - 5
batch_size:
  desc: null
  value: 256
data_format:
  desc: null
  value: null
dataset:
  desc: null
  value: celedebug
default_config:
  desc: null
  value: false
dissimilarity_type:
  desc: null
  value: L1
ent_emb_dim:
  desc: null
  value: 50
keywords:
  desc: null
  value:
  - gene
  - phenotype
  - interaction
  - disease_plus_ortho
  - disease-ontology
  - phenotype-ontology
  - expression_pattern
loss_fn:
  desc: null
  value: margin
lr:
  desc: null
  value: 0.0001
margin:
  desc: null
  value: 1.0
method:
  desc: null
  value: TransE
n_epochs:
  desc: null
  value: 20
n_filters:
  desc: null
  value: 500
normalize_parameters:
  desc: null
  value: true
ouput:
  desc: null
  value: ./
query:
  desc: null
  value: null
rel_emb_dim:
  desc: null
  value: 50
save_data:
  desc: null
  value: false
save_model:
  desc: null
  value: false
scalar_share:
  desc: null
  value: 0.5
split_ratio:
  desc: null
  value: 0.8
weight_decay:
  desc: null
  value: 0.0001
